<?php
/**
 *
 * @var $this \Cubex\View\Layout
 *
 * This is your default layout file, variables in this file act as placeholders for named nested views
 *
 */
?>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
      <ul class="nav nav-tabs nav-stacked">
        <li><a href="/">Home</a></li>
        <li><a href="/">Performance</a></li>
      </ul>
    </div>
    <div class="span10">
      <?php echo $this->renderNest("content", "main-content"); ?>
    </div>
  </div>
</div>
